### ISSUE TITLE
Kan niet de Homey Community store app instaleren op de homey:

### ISSUE THREAD

**Issue by Jansiesling** [MaxvandeLaar/homey-community-store-installer#15]
Dag Max,
Ik heb een probleem met het instaleren van de community app op de Homey.
Ik schakel de AVG virus scanner en wall uit.
Hij blijft dan gewoon draaien, gisteren was de homey niet meer bereikbaar, deze opnieuw opgestart via de stekker er uit methode.
Deze blijft nu dan half uur draaien zonder dat er wat gebeurd in de homey.
kan het misschien liggen aan het feit dat de homey via wiffi verbonden is met de router de computer is aan zelfde router verbonden met een LAN kabel.
Ik weet het nu niet meer. Computer ook al een x opnieuw opgestart om te kijken of daar een probleem zat.
Weet jij nog een oplossing?
Vr Gr Jan
![IMG_20210217_220144](https://user-images.githubusercontent.com/77204539/108408280-27adf380-7225-11eb-8344-3e85dcc86f66.jpg)

**Comment by MaxvandeLaar** [comment]
Dit probleem heb ik de afgelopen dagen wat vaker langs zien komen. Het staat op mijn todo lijst om op te pakken. 

Een workaround is om via de command line 'homey logout' uit te voeren. Dit werkt alleen indien je NPM met Homey als een dependency op je systeem hebt geïnstalleerd. Hoe dat werkt vind je hier https://apps-sdk-v3.developer.athom.com/tutorial-Getting%20Started.html

**Comment by Jansiesling** [comment]
Dag max,

Dank dat je dit aan wil pakken, snap ook wel dat dit niet van vandaag op morgen geregeld is. Dat van workaround, snap ik niet helemaal, daar ga ik eens rustig voor zitten.

Kun je mij een slack abbo aanbieden dat kan ik dat medium ook gebruiken.

Vriendelijke groet Jan


verstuurd vanaf mijn mobiel. vriendelijke groet Jan


Van: Max <notifications@github.com>Verstuurd: donderdag 18 februari 2021 22:05Aan: MaxvandeLaar/homey-community-store-installerCc: Jansiesling; AuthorOnderwerp: Re: [MaxvandeLaar/homey-community-store-installer] Kan niet de Homey Community store app instaleren op de homey: (#15)

Dit probleem heb ik de afgelopen dagen wat vaker langs zien komen. Het staat op mijn todo lijst om op te pakken.

Een workaround is om via de command line 'homey logout' uit te voeren. Dit werkt alleen indien je NPM met Homey als een dependency op je systeem hebt geïnstalleerd. Hoe dat werkt vind je hier https://apps-sdk-v3.developer.athom.com/tutorial-Getting%20Started.html

**Comment by MaxvandeLaar** [comment]
@Jansiesling Je kan je aanmelden bij ons community slack via deze link [https://homey.community/contact/](https://homey.community/contact/)

**Comment by Nnk2** [comment]
> Dit probleem heb ik de afgelopen dagen wat vaker langs zien komen. Het staat op mijn todo lijst om op te pakken.
> 
> Een workaround is om via de command line 'homey logout' uit te voeren. Dit werkt alleen indien je NPM met Homey als een dependency op je systeem hebt geïnstalleerd.

Hallo Max, 
Ik heb hetzelfde probleem als hierboven beschreven, nadat ik:
- Mijn werkende Homey (2016) met de community store app heb moeten vervangen door een nieuwe Homey pro
- Een restore heb gedaan 

Al geprobeerd: 
- Homey reboot
- Nieuwe download van de (Windows) HCS installer app (die hetzelfde resultaat geeft en op "Installing app" blijft hangen
- Op Windows 10 NPM en Homey tools geïnstalleerd
- Een "Homey Login" (Lukt) en daarna "Homey Logout" gedaan, vanuit de windows commandline 
- Opnieuw geprobeerd de HCS Installer te draaien, met hetzelfde resultaat: "Installing App" 

Heb je nog andere suggesties voor me? 
Ik kan nu mijn Nest apparaten niet meer gebruiken ...

Alvast dank!

**Comment by MaxvandeLaar** [comment]
@Nnk2 Goed om te lezen dat het gelukt is. 

Weet dat als je zelf niet een workaround had gevonden, dan had ik nog een werkend alternatief ;)
